### PR TITLE
beautifying resources page

### PR DESCRIPTION
**Pull request by lizmaidl**
adding tabs, more info, rearranging into discrete sections

### CODE REVIEW

**Comment by justinrporter** [comment]
So, it looks like you're using large numbers of &nbsp characters to center stuff. Have you looked at centering and tables in HTML? I think those might provide a better solution to the formatting your looking for...

http://www.htmlcodetutorial.com/linepar/_CENTER.html
http://www.html.am/html-codes/tables/

**Comment by lizmaidl** [comment]
i think this page is about ready to go live. only thing is that the respectacle link doesn't seem to work for me. not sure how to fix this...

**Comment by radhikajain** [comment]
I added that today…maybe I wrote it in wrong? Do you mind double-checking how I wrote it in the code?

**Comment by lizmaidl** [comment]
The code looked okay to me. I tried a few different things, but whenever I clicked on it it said "not found" and took me to like: localhost:8000/app//respectacle.org

**Comment by justinrporter** [comment]
If you look closely at the the quotes around the href in the link tag, you'll see that the respectable link uses a curly, or "smart" quote (`“`) and a straight quote (`"`). I have no idea why this causes the observed behavior, but I think that's the problem.

Also, I just want to say I am _so proud_ of you guys! You're officially collaborating with GitHub to develop a webpage--there are probably undergrads studying computer science who don't know how to do that!

**Comment by lizmaidl** [comment]
you're gonna make me cry.

fixed. now i think it's ready to go live!

**Comment by justinrporter** [comment]
@lizmaidl @radhikajain I made some changes using some of the modern web development tools we're using on the site that I didn't explain to you guys to
1. make better use of the horizontal space and make it a bit more mobile-compatible. They look like
   
   ```
       <div class="col-xs-6 col-lg-4">
   ```
2. I also removed a lot of the hard-breaks and replaced them with paragraph blocks (`<p>`) and container divs (`<div class="container">`)
3. I also made the headers links, rather than including the URLs as plain text in the body of each of the elements.

Have a look at the changes to learn some new HMTL syntax (especially @lizmaidl) and I'd love to hear your thoughts!

For some ideas/features to use in your HTML in the future, you can check out [bootstrap](http://getbootstrap.com/css) which is the UI framework we're using (mostly--don't use anything under the JavaScript tab). It's partially because of bootstrap that we rely so heavily on `<div>` blocks throughout the website. For example, you might check out [inline lists](http://getbootstrap.com/css/#inline) as an alternative to what I've done with the hotlines section.

**Comment by lizmaidl** [comment]
okay i moved a few things around to make the page more symmetric as a whole, and i think it's probably about done now. the only thing i can't figure out is why the FQHC section isn't tabbed in like the rest of them. i looked at it, but i have no idea what the issue is. same thing with the hotlines section; i'm going to assume it got messed up when i was rearranging stuff.

**Comment by justinrporter** [comment]
Awesome! checked it out, fixed it. I'm declaring this done, and putting out for deployment tonight!

**Pull request merged**
