### PR TITLE
Espanol

### PR DESCRIPTION
**Pull request by justinrporter**
Make small spanish page

### CODE REVIEW

**Comment by justinrporter** [comment]
These first two commits are just reverting reversions in master that got rid of the en espanol site on master.

**Comment by lizmaidl** [comment]
on second thought, rather than having this as a stub under the 'for patients' tab, this should probably have its own tab, so it's more accessible to spanish-speaking patients. how do we change this, then?

we should also probably have one of those circle image things like on the front page, just for continuity.

**Comment by justinrporter** [comment]
Works for me. I'm sort of plus/minus on the new circle, but I think having an "En Espanol" tab is a good idea. I've done that. Check it out.

**Comment by radhikajain** [comment]
Justin when you say check it out, can you remind me how to do that? i.e. how to look at a draft version of the page?

**Comment by lizmaidl** [comment]
all done! i think this is ready to be merged (as long as you give it the okay, justin).

**Comment by lizmaidl** [comment]
image

**Comment by justinrporter** [comment]
BALLIN'

**Comment by radhikajain** [comment]
I should be able to see this now right?

**Comment by justinrporter** [comment]
@radhikajain good catch! It looks like the auto-pull last night didn't work. The issue is resolved now.

**Comment by radhikajain** [comment]
It worked!!

This is amazing Liz, thank you!!

**Pull request merged**
